project_name: http-dump
env:
  - GO111MODULE=on
builds:
  - main: ./cmd/http-dump
    binary: http-dump
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
